org.gradle.jvmargs=-Xmx1024m -XX:+UseSerialGC -Dfile.encoding=UTF-8
org.gradle.workers.max=1
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.enableAapt2Daemon=false
android.aapt2FromMavenOverride=/data/data/com.termux/files/home/Android/Sdk/build-tools/34.0.0/aapt2
